fix README filename suffix
current master branch failed to install due to a file not found error in setup.py
```
with open('README.rst') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'README.rst'
```